# Generated by Django 5.2.5 on 2025-09-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('category', models.CharField(choices=[('body', 'Body Parts'), ('exterior', 'Exterior'), ('interior', 'Interior'), ('audio', 'Audio & Electronics'), ('parts', 'Parts'), ('performance', 'Performance'), ('lighting', 'Lighting')], max_length=50)),
                ('stock_status', models.BooleanField(default=True)),
                ('warranty', models.IntegerField(default=0)),
                ('delivery_days', models.IntegerField(default=0)),
                ('return_days', models.IntegerField(default=0)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('trim', models.CharField(blank=True, max_length=50, null=True)),
                ('engine', models.CharField(blank=True, max_length=50, null=True)),
                ('drive_type', models.CharField(blank=True, max_length=50, null=True)),
                ('body_class', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
