# Generated by Django 5.2.5 on 2025-09-05 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('category', models.CharField(choices=[('body', 'Body Parts'), ('exterior', 'Exterior'), ('interior', 'Interior'), ('audio', 'Audio & Electronics'), ('parts', 'Parts'), ('performance', 'Performance'), ('lighting', 'Lighting')], max_length=50)),
                ('stock_status', models.BooleanField(default=True)),
                ('warranty', models.IntegerField(default=0)),
                ('delivery_days', models.IntegerField(default=0)),
                ('return_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='part',
            name='category',
        ),
        migrations.RemoveField(
            model_name='part',
            name='delivery_days',
        ),
        migrations.RemoveField(
            model_name='part',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='part',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.RemoveField(
            model_name='part',
            name='price',
        ),
        migrations.RemoveField(
            model_name='part',
            name='return_days',
        ),
        migrations.RemoveField(
            model_name='part',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='part',
            name='stock_status',
        ),
        migrations.RemoveField(
            model_name='part',
            name='warranty',
        ),
        migrations.AddField(
            model_name='part',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='parts.partsadmin'),
        ),
    ]
