# Generated by Django 5.2.5 on 2025-09-05 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_partsadmin_remove_part_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='parts.partsadmin'),
        ),
    ]
