# Generated by Django 5.2.5 on 2025-09-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_part_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsadmin',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='parts/images'),
        ),
    ]
