# Generated by Django 5.2.5 on 2025-09-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_partsadmin_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsadmin',
            name='category',
            field=models.CharField(choices=[('body', 'Body Parts'), ('exterior', 'Exterior'), ('interior', 'Interior'), ('audio', 'Audio & Electronics'), ('parts', 'Parts'), ('performance', 'Performance'), ('lighting', 'Lighting'), ('uncategorized', 'Uncategorized')], max_length=50),
        ),
    ]
