# Generated by Django 5.2.5 on 2025-09-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_alter_partsadmin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsadmin',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
