# Generated by Django 5.2.5 on 2025-09-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_alter_partsadmin_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partsadmin',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='partsadmin',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partsadmin',
            name='category',
            field=models.CharField(choices=[('body', 'Body Parts'), ('exterior', 'Exterior'), ('interior', 'Interior'), ('audio', 'Audio & Electronics'), ('parts', 'Parts'), ('performance', 'Performance'), ('lighting', 'Lighting'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
    ]
