# Generated by Django 5.2.5 on 2025-09-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_category_partsadmin_new_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsadmin',
            name='category',
        ),
    ]
